name: Over The Hedge
sha1: eacf7706f034b2e27a0f5a89d61e3e36d6353ea8
options:
  basename: SLUS_213.00
  target_path: SLUS_213.00.rom
  elf_path: build/SLUS_213.00.elf
  base_path: ..
  platform: ps2
  compiler: EEGCC

  gp_value: 0x00492770
  ld_gp_expression: cod_SDATA_START + 0x7FF0

  asm_path: asm
  src_path: src
  build_path: build

  ld_script_path: SLUS_213.00.ld
  ld_dependencies: True
  ld_wildcard_sections: True
  ld_bss_contains_common: True

  create_asm_dependencies: True

  # Enabled to allow Splat to automatically resolve boundaries for new files
  find_file_boundaries: True

  o_as_suffix: True

  symbol_addrs_path:
    - symbol_addrs.txt
  reloc_addrs_path:
    - reloc_addrs.txt

  undefined_funcs_auto_path: undefined_funcs_auto.txt
  undefined_syms_auto_path: undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  named_regs_for_c_funcs: False

  section_order:
    - .text
    - .data
    - .rodata
    - .gcc_except_table
    - .sdata
    - .sbss
    - .bss

  auto_link_sections:
    - .data
    - .rodata
    - .gcc_except_table
    - .sdata
    - .sbss
    - .bss

segments:
  - name: cod
    type: code
    start: 0x000000
    vram: 0x00100000
    bss_size: 0x427FD
    subalign: null
    subsegments:
      - [0x00100000, c, main]
      - [0x002679B8, c, engine/resource_loader]
      - [0x00290000, cpp, actors/FOO]
      - [0x002A0000, cpp, game/CharacterManager]
      - [0x002B0000, asm, entry]
      - [0x30A130, textbin, cod/30A130]
      - [0x312800, data, cod/312800]
      - [0x321200, rodata, cod/321200]
      - [0x38A680, gcc_except_table, cod/38A680]
      - [0x38A780, sdata, cod/38A780]
      - { type: sbss, vram: 0x0048AF00, name: cod/0048AF00 } # .sbss
      - { type: bss, vram: 0x0048B480, name: cod/0048B480 } # .bss
  - [0x38AEDC]
